comiccollector/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from books import views as books_views

urlpatterns = [
    url(r'^accounts/profile/$',
        books_views.UserProfileView.as_view(),
        name='user-profile'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'author-autocomplete/$',
        books_views.AuthorAutocomplete.as_view(),
        name='author-autocomplete'),
    url(r'issue-autocomplete/$',
        books_views.IssueAutocomplete.as_view(),
        name='issue-autocomplete'),
    url(r'book-autocomplete/$',
        books_views.BookAutoComplete.as_view(),
        name='book-autocomplete'),
    url(r'series-autocomplete',
        books_views.SeriesAutocomplete.as_view(),
        name='series-autocomplete'),
    url(r'^$',
        books_views.HomePageView.as_view(),
        name='home-page'),
    url(r'^comic/(?P<book_id>\d+)/$',
        books_views.BookDetailView.as_view(),
        name='comic-detail'),
    url(r'^collection/$',
        books_views.CollectionView.as_view(),
        name='collection'),
    url(r'^search/$',
        books_views.SearchView.as_view(),
        name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comiccollector/books/models.py
import isbnlib
from django.conf import settings
from django.contrib.postgres.fields import HStoreField
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.utils.safestring import mark_safe
from django.utils.timezone import now
from imagekit import ImageSpec, register
from imagekit.models import ImageSpecField
from imagekit.utils import get_field_info
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from pilkit import processors

from .choices import book_types, image_source

YEARS = [(x, x) for x in range(1950, now().year + 1)]
YEARS.append((9999, 'ongoing'))


class Book(MPTTModel):
    """
    Book Model
    """
    title = models.TextField(
        verbose_name='Title')
    isbn = models.CharField(
        verbose_name='ISBN',
        max_length=30,
        unique=True)
    publication_date = models.DateField(
        verbose_name='Publication Date',
        null=True,
        blank=True)
    author_artist = models.ManyToManyField(
        blank=True,
        to='AuthorArtist',
        verbose_name='Author/Artists')
    issues = models.ManyToManyField(
        to='Issue',
        related_name='books',
        blank=True)
    series = models.ManyToManyField(
        to='Series',
        related_name='books',
        blank=True)
    series_mapping = HStoreField(
        default=dict(),
        blank=True)
    number = models.PositiveIntegerField(
        verbose_name='Volume number',
        help_text='Volume number if the book is part of a series of volumes',
        null=True,
        blank=True)
    book_type = models.CharField(
        max_length=25,
        verbose_name='Book Type',
        help_text='Type of book (such as TPB or Omnibus)',
        choices=book_types,
        default=book_types[0][0])
    description = models.TextField(
        help_text='Book description',
        blank=True)
    large_cover = models.URLField(
        max_length=1024,
        help_text='URL to large cover image',
        blank=True)
    medium_cover = models.URLField(
        max_length=1024,
        help_text='URL to medium cover image',
        blank=True)
    small_cover = models.URLField(
        max_length=1024,
        help_text='URL to small cover image',
        blank=True)
    amazon_link = models.URLField(
        max_length=1024,
        help_text='Amazon detail page',
        blank=True)
    previous = TreeForeignKey(
        to='self',
        help_text='The previous book in ongoing story',
        related_name='next',
        null=True,
        blank=True,
        on_delete=models.SET_NULL)
    marvel_id = models.PositiveIntegerField(
        verbose_name='Marvel ID',
        blank=True,
        null=True,
        unique=True)
    page_count = models.PositiveIntegerField(
        blank=True,
        null=True)

    @property
    def related_books(self):
        same_series = Q(series__id__in=self.series.values('id'))
        children = Q(id__in=self.get_children().values('id'))
        parent = Q(id=self.previous.id) if self.previous else Q()
        return Book.objects.filter(same_series | children | parent).exclude(id=self.id).order_by('?')[:12]

    def image_tag(self, size='large'):
        attr = '{}_cover'.format(size)
        src = getattr(self, attr, '')
        if src == '':
            src = self.large_cover
        return mark_safe(
            '<img src="{src}" class="{size} img-responsive" />'.format(
                src=src,
                size=size)
        )
    image_tag.short_description = 'Cover image'

    def thumbnail(self):
        return self.image_tag(size='small')

    def preview_image(self):
        return self.image_tag(size='medium')

    def amazon_button(self):
        return mark_safe(
            '<a href="{.amazon_link}" class="amazon-button" target="_blank">'
            '<i class="fa fa-amazon"></i> Amazon Page</a>'.format(self))
    amazon_button.short_description = 'Amazon page'

    def isbn_mask(self):
        return isbnlib.mask(self.isbn, '-')

    def has_description(self):
        return self.description not in ('', None)
    has_description.boolean = True

    @property
    def issue_count(self):
        return self.issues.count()

    def has_previous(self):
        return self.previous is not None
    has_previous.boolean = True

    def has_next(self):
        return self.get_children().count() > 0
    has_next.boolean = True

    def last(self):
        if self.has_next():
            return self.get_descendants()[self.get_descendant_count() - 1]

    def get_absolute_url(self):
        return reverse('comic-detail', kwargs={'book_id': self.id})

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.isbn = isbnlib.canonical(self.isbn)
        return super().save(
            force_insert,
            force_update,
            using,
            update_fields)

    def __str__(self):
        return self.title

    class Meta(object):
        permissions = (
            ('view_book', 'Can view and search for books'),
        )

    class MPTTMeta(object):
        parent_attr = 'previous'


class AuthorArtist(models.Model):
    """
    Simple model of an Author, Artist etc.
    """
    name = models.TextField(
        verbose_name='Author or Artist Name')
    role = models.CharField(
        max_length=50,
        blank=True)

    def __str__(self):
        return '{0.name} ({0.role})'.format(self)

    class Meta(object):
        verbose_name = 'Author or Artist'
        verbose_name_plural = 'Authors and Artists'
        unique_together = ('name', 'role')


class Issue(models.Model):
    """
    Although technically a book in real life, for simplicity this is a basic
    model that just tracks an issue number with a :class:`series<Series>`
    """
    number = models.PositiveIntegerField(
        verbose_name='Issue Number')
    suffix = models.CharField(
        max_length=25,
        verbose_name='Issue number suffix',
        blank=True)
    series = models.ForeignKey(
        to='Series',
        related_name='issues')

    class Meta(object):
        ordering = ['series__name', 'number', 'suffix']
        unique_together = ('number', 'suffix', 'series')

    def __str__(self):
        suffix = '.%s' % self.suffix if self.suffix else ''
        return '%s #%d%s' % (self.series.name, self.number, suffix)


class Series(models.Model):
    """
    A very simple model with just the name of the series
    """
    name = models.TextField(unique=True)
    start_year = models.IntegerField(
        choices=YEARS,
        default=1950)
    end_year = models.IntegerField(
        choices=YEARS,
        default=9999)

    class Meta(object):
        verbose_name_plural = 'Series'
        ordering = ['name']

    def __html__(self):
        return self.__str__()

    def __str__(self):
        return mark_safe('%s (%s &mdash; %s)' % (
            self.name,
            self.get_start_year_display(),
            self.get_end_year_display()))


class Event(models.Model):
    """
    Another simple model with just the name of the event
    """
    name = models.TextField(
        verbose_name='Event name',
        unique=True)
    books = models.ManyToManyField(
        to='Book',
        verbose_name='Books',
        related_name='events',
        blank=True)

    def __str__(self):
        return self.name


class Collection(models.Model):
    """
    Collection model to keep a user's owned, wanted, read etc books
    """
    user = models.OneToOneField(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='collection')
    books = models.ManyToManyField(
        to='Book',
        through='CollectedBooks')

    def in_collection(self, book: Book) -> models.query.QuerySet:
        return CollectedBooks.objects.filter(book=book, collection=self)

    def get_state(self, book: Book) -> str:
        in_collection = self.in_collection(book)
        if in_collection.count() > 0:
            return in_collection.first().state
        return 'unowned'


class CollectedBooks(models.Model):
    collection = models.ForeignKey(
        to='Collection',
        related_name='collected_books')
    book = models.ForeignKey(
        to='Book',
        related_name='collections')
    owned = models.BooleanField(
        default=True)
    read = models.BooleanField(
        default=False)

    @property
    def state(self) -> str:
        state = 'wanted'
        if self.read:
            state = 'read'
        elif self.owned:
            state = 'owned'
        return state

    class Meta(object):
        unique_together = ('collection', 'book')
        verbose_name_plural = 'Collected Books'


class BookImage(models.Model):
    upload_path = 'img/books'
    thumbnail_width = 130
    preview_width = 210
    book = models.ForeignKey(
        'Book',
        related_name='images')
    source = models.CharField(
        max_length=20,
        choices=image_source,
        default=image_source[0][0])
    image = models.ImageField(
        upload_to=upload_path,
        max_length=1024,
        width_field='width',
        height_field='height')
    width = models.PositiveIntegerField(
        default=0)
    height = models.PositiveIntegerField(
        default=0)
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[
            processors.Thumbnail(thumbnail_width)
        ])
    image_preview = ImageSpecField(
        source='image',
        processors=[
            processors.Thumbnail(preview_width)
        ])
    cropped_thumbnail = ImageSpecField(
        source='image',
        processors=[
            processors.Thumbnail(thumbnail_width),
            processors.Crop(thumbnail_width, thumbnail_width, anchor=processors.Anchor.TOP)
        ])
    cropped_preview = ImageSpecField(
        source='image',
        processors=[

comiccollector/books/forms.py
from dal import autocomplete
from django import forms

from .choices import collection_actions
from .models import Book, Issue, Series


class SearchForm(forms.Form):
    q = forms.CharField(
        max_length=1024,
        widget=forms.TextInput(attrs={'id': 'searchbar'}))


class BookAdminForm(forms.ModelForm):
    isbn = forms.CharField(
        max_length=30,
        required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.fields.get('previous') is not None:
            self.fields['previous'].level_indicator = ''

    class Meta(object):
        model = Book
        fields = '__all__'
        widgets = {
            'author_artist': autocomplete.ModelSelect2Multiple(
                url='author-autocomplete',
                attrs={'data-width': 'resolve'}),
            'issues': autocomplete.ModelSelect2Multiple(
                url='issue-autocomplete',
                attrs={'data-width': 'resolve'}),
            'cover_image': forms.HiddenInput(),
            'amazon_link': forms.HiddenInput(),
            'previous': autocomplete.ModelSelect2(
                url='book-autocomplete',
                attrs={'data-width': 'resolve'}),
            'series': autocomplete.ModelSelect2Multiple(
                url='series-autocomplete',
                attrs={'data-width': 'resolve'}),
            'title': forms.TextInput(),
        }


class IssueForm(forms.ModelForm):
    series = forms.ModelChoiceField(
        Series.objects.all(),
        label='Series',
        widget=autocomplete.ModelSelect2(
            url='series-autocomplete',
            attrs={'data-width': 'resolve'})
    )
    number = forms.IntegerField(
        label='Number',
        min_value=0)
    suffix = forms.CharField(
        label='Suffix',
        max_length=10,
        strip=True,
        required=False)

    def __init__(self, *args, instance=None, **kwargs):
        super().__init__(*args, instance=instance, **kwargs)
        if instance is not None:
            self.fields['series'].initial = instance.issue.series
            self.fields['number'].initial = instance.issue.number
            self.fields['suffix'].initial = instance.issue.suffix

    def save(self, commit=True):
        super().save(commit)
        if self.instance.id is None:
            issue, _ = Issue.objects.get_or_create(
                series=self.cleaned_data['series'],
                number=self.cleaned_data['number'],
                suffix=self.cleaned_data['suffix'])
            self.instance.issue_id = issue.id
        else:
            for f_name in self.changed_data:
                setattr(self.instance.issue, f_name, self.cleaned_data[f_name])
            self.instance.issue.save()
        return self.instance

    class Meta(object):
        model = Issue.books.through
        fields = ('series', 'number', 'suffix')
        widgets = {
            'series': autocomplete.ModelSelect2(
                url='series-autocomplete',
                attrs={'data-width': 'resolve'}),
        }


class SeriesForm(forms.ModelForm):
    name = forms.CharField(max_length=255)
    start_year = forms.IntegerField(min_value=1950, max_value=9999)
    end_year = forms.IntegerField(min_value=1950, max_value=9999)

    def __init__(self, *args, instance=None, **kwargs):
        super().__init__(*args, instance=instance, **kwargs)
        if instance is not None:
            self.fields['name'].initial = instance.series.name
            self.fields['start_year'].initial = instance.series.start_year
            self.fields['end_year'].initial = instance.series.end_year

    def save(self, commit=True):
        super().save(commit)
        if self.instance.id is None:
            series, _ = Series.objects.get_or_create(
                name=self.cleaned_data['name'],
                start_year=self.cleaned_data['start_year'],
                end_year=self.cleaned_data['end_year'])
            self.instance.series_id = series.id
        else:
            for f_name in self.changed_data:
                setattr(self.instance.series, f_name, self.cleaned_data[f_name])
            self.instance.series.save()
        return self.instance

    class Meta(object):
        model = Series.books.through
        fields = ('name', 'start_year', 'end_year')


class BookDetailForm(forms.Form):
    book = forms.ModelChoiceField(
        queryset=Book.objects.all(),
        widget=forms.HiddenInput)
    action = forms.ChoiceField(
        choices=collection_actions,
        widget=forms.HiddenInput)


class SeriesSearchForm(forms.Form):
    name = forms.CharField(max_length=255)
    original = forms.CharField(max_length=255)
    start_year = forms.IntegerField(
        max_value=9999,
        min_value=1950,
        required=False)
    end_year = forms.IntegerField(
        max_value=9999,
        min_value=1950,
        required=False)

comiccollector/templates/books/book_detail.html
{% extends "base.html" %}

{% block extra_nav %}
  {% if user.is_staff %}
    <li>
      <a href="{% url 'admin:books_book_change' book.id %}" class="">
        <i class="fa fa-pencil"></i> Edit this
      </a>
    </li>
    <li class="divider"></li>
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <h1 class="page-header">{{ book.title }}
        <br/>
        <small>{{ view.get_author }}</small>
      </h1>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <picture>
        <source media="(max-width: 768px)" srcset="{{ book.images.first.image_preview.url }}">
        <img src="{{ book.images.first.image.url }}" class="img-responsive img-rounded center-block">
      </picture>
    </div>
    <div class="col-xs-12 col-sm-8">
      <p>{{ book.description }}</p>
      <h4>Collected Issues</h4>
      <ul>
        {% for issue in book.issues.all %}
          <li>{{ issue }}
            {% if issue.id in view.owned_issues %}
              <i class="fa fa-check state read" title="Owned"></i>
            {% endif %}</li>
        {% endfor %}
      </ul>
      <p>
      <form method="post">
        {% csrf_token %}
        <input type="hidden" name="book" value="{{ book.id }}">
        {% if state == 'unowned' or state == 'wanted' %}
          <button
              class="btn btn-default change-icon btn-responsive"
              type="submit"
              name="action"
              value="add-collection">
            <i class="fa fa-bookmark-o"></i>
            <i class="fa fa-bookmark"></i>
            &nbsp;Add to collection
          </button>
        {% else %}
          <button
              class="btn btn-default change-icon btn-responsive"
              type="submit"
              name="action"
              value="remove-collection">
            <i class="fa fa-bookmark"></i>
            <i class="fa fa-bookmark-o"></i>
            &nbsp;Remove from collection
          </button>
        {% endif %}
        {% if state != 'wanted' %}
          <button
              class="btn btn-default change-icon btn-responsive"
              type="submit"
              name="action"
              value="add-wishlist">
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star"></i>
            &nbsp;Add to wishlist
          </button>
        {% else %}
          <button
              class="btn btn-default change-icon btn-responsive"
              type="submit"
              name="action"
              value="remove-wishlist">
            <i class="fa fa-star"></i>
            <i class="fa fa-star-o"></i>
            &nbsp;Remove from wishlist
          </button>
        {% endif %}
        {% if state != 'read' %}
          <button
              class="btn btn-default change-icon btn-responsive"
              type="submit"
              name="action"
              value="add-read">
            <i class="fa fa-square-o"></i>
            <i class="fa fa-check-square-o"></i>
            &nbsp;Mark as read
          </button>
        {% else %}
          <button
              class="btn btn-default change-icon btn-responsive"
              type="submit"
              name="action"
              value="remove-read">
            <i class="fa fa-check-square-o"></i>
            <i class="fa fa-square-o"></i>
            &nbsp;Mark as unread
          </button>
        {% endif %}
      </form>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="reading-order-buttons">
        {% if book.has_previous %}
          <div class="pull-left">
            <a href="{{ book.get_root.get_absolute_url }}"
               class="btn btn-default btn-responsive">
              <i class="fa fa-chevron-left"></i><i class="fa fa-chevron-left"></i> First in story
            </a>
            <a href="{{ book.previous.get_absolute_url }}"
               class="btn btn-default btn-responsive"><i class="fa fa-chevron-left"></i> Preious in story</a>
          </div>
        {% endif %}
        {% if book.has_next %}
          <div class="pull-right">
            <a href="{{ book.get_children.first.get_absolute_url }}"
               class="btn btn-default btn-responsive">Next in story <i class="fa fa-chevron-right"></i>
            </a>
            <a href="{{ book.last.get_absolute_url }}"
               class="btn btn-default btn-responsive">
              Last in story <i class="fa fa-chevron-right"></i><i class="fa fa-chevron-right"></i>
            </a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
  {% if book.related_books %}
    <div class="row">
      <div class="col-xs-12">
        <h3 class="page-header">Related Comics</h3>
      </div>
      {% include 'books/includes/related_gallery.html' with books=book.related_books %}
    </div>
  {% endif %}
  {% include 'books/includes/book_modal.html' %}
{% endblock %}

{% block footer_right %}
  Data provided by Marvel. © 2014 Marvel
{% endblock %}


{% block javascripts %}
  {{ block.super }}
  <script type="application/javascript">
    {% include 'books/includes/js/book_modal.js' %}
  </script>
{% endblock %}

comiccollector/templates/books/collection.html
{% extends "base.html" %}

{% block content %}
  <div class="col-md-12">
    <h2>
      {% block page_title %}
        Your collection
      {% endblock %}
    </h2>
    {% block list %}
      {% include 'books/includes/book_gallery.html' %}
    {% endblock %}
    {% if is_paginated %}
      {% include 'books/includes/pagination.html' %}
    {% endif %}
  </div>
  {% block modal %}
    {% include 'books/includes/book_modal.html' %}
  {% endblock %}
{% endblock %}

{% block javascripts %}
  {{ block.super }}
  <script type="application/javascript">
    {% include 'books/includes/js/book_modal.js' %}
  </script>
{% endblock %}

comiccollector/templates/books/marvel_update_results.html
{% extends 'admin/change_list.html' %}
{% load i18n staticfiles %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/books/extra_admin.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/books/extra_admin.css.map' %}">
{% endblock %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">Home</a>
    &rsaquo; <a href="{% url 'admin:app_list' 'books' %}">Books</a>
    &rsaquo; <a href="{% url 'admin:books_book_changelist' %}">Books</a>
    &rsaquo; <a href="{% url 'admin:books_book_change' object.id %}">
    {{ object.title }}
  </a>
    &rsaquo; {{ title }}

  </div>
{% endblock %}

{% block search %}
  <p>
    {% block intro %}
      Below are the matches from the Marvel API for <strong>{{ object.title }}</strong>.<br>
      Please choose one to update the extra information for this book, or search the Marvel API manually,
      to find a closer match
    {% endblock %}
  </p>
  <div id="toolbar">
    <form id="changelist-search" method="get">
      <div><!-- DIV needed for valid HTML -->
        <label for="searchbar"><img src="{% static 'admin/img/search.svg' %}" alt="Search"></label>
        <input id="searchbar" maxlength="1024" name="q" type="text">
        <button class="button" type="submit" name="provider" value="marvel">Search Marvel</button>
        {% if paginator.count > 0 %}
          Page {{ page_obj.number }} of {{ paginator.num_pages }} ({{ paginator.count }} results)
        {% else %}
          No results
        {% endif %}
      </div>
    </form>
  </div>
{% endblock %}
{% block date_hierarchy %}{% endblock %}
{% block result_list %}
  <div class="results">
    <table id="result_list" class="table table-striped">
      <thead>
      <tr>
        <th scope="col" class="column-thumbnail">
          <div class="text"><span>Thumbnail</span></div>
          <div class="clear"></div>
        </th>
        <th scope="col" class="column-title">
          <div class="text">Title</div>
          <div class="clear"></div>
        </th>
        <th scope="col" class="column-title">
          <div class="text">Book Type</div>
          <div class="clear"></div>
        </th>
        <th scope="col" class="column-title">
          <div class="text">ISBN</div>
          <div class="clear"></div>
        </th>
        <th scope="col" class="column-title">
          <div class="text">Marvel ID</div>
          <div class="clear"></div>
        </th>
        <th scope="col" class="column-title">
          <div class="text">Description?</div>
          <div class="clear"></div>
        </th>
        <th>
          <div class="text">{% block action_header %}Update fields{% endblock %}</div>
        </th>
      </tr>
      </thead>
      <tbody>
      {% for book in books %}
        <tr>
          <th class="field-thumbnail"><img src="{{ book.small_cover }}" class="small"></th>
          <td class="field-title">{{ book.title }}</td>
          <td class="field-title">{{ book.get_book_type_display }}</td>
          <td class="field-title">{{ book.isbn }}</td>
          <td class="field-marvel_id">{{ book.marvel_id }}</td>
          <td class="field-has_description">
            {% if book.has_description %}
              <i class="fa fa-check-circle green"></i>
            {% else %}
              <i class="fa fa-times-circle red"></i>
            {% endif %}
          </td>
          <td class="field-select">
            <form action="{% url "admin:update-marvel" book_id=object.id %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="title" value="{{ book.title }}">
              <input type="hidden" name="isbn" value="{{ book.isbn }}">
              <input type="hidden" name="book_type" value="{{ book.book_type }}">
              <input type="hidden" name="publication_date" value="{{ book.publication_date|date:"Y-m-d" }}">
              <input type="hidden" name="description" value="{{ book.description|default:"" }}">
              <input type="hidden" name="page_count" value="{{ book.page_count }}">
              <input type="hidden" name="marvel_id" value="{{ book.marvel_id }}">
              <input type="hidden" name="series_mapping" value="{{ book.series_mapping }}">
              {% block action_buttons %}
                <button type="submit" name="action" value="missing" class="btn btn-success btn-xs">Update missing
                </button>
                <button type="submit" name="action" value="all" class="btn btn-success btn-xs">Update all</button>
              {% endblock %}
            </form>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}
{% block pagination %}
  {% include 'books/includes/admin_pagination.html' %}
{% endblock %}

comiccollector/templates/books/search_results.html
{% extends 'books/collection.html' %}

{% block page_title %}
  Results for "{{ request.GET.q }}"
{% endblock %}

{% block list %}
  {% include 'books/includes/search_gallery.html' %}
{% endblock %}

comiccollector/templates/books/series_matches.html
{% extends 'admin/base_site.html' %}
{% load staticfiles %}
{% load books_tags %}

{% block extrastyle %}
  <link rel="stylesheet" href="{% static 'css/books/extra_admin.css' %}">
{% endblock %}

{% block content %}

  {% block intro %}
    <p>
      Below are the series found within the blurb of {{ book.title }}.
    </p>
    <blockquote>
      {{ book.description|highlight:collecting }}
    </blockquote>
    <p>
      Any that were unknown will be editable.
      Please enter a valid search string to search for matching series for that match
    </p>
  {% endblock %}

  <div class="results">
    <table id="result_list">
      <thead>
      <tr>
        {% block table_header %}
          <th scope="col" class="column-name">
            <div class="text"><span>Series Name</span></div>
            <div class="clear"></div>
          </th>
          <th scope="col" class="column-start-year">
            <div class="text">Start Year</div>
            <div class="clear"></div>
          </th>
          <th scope="col" class="column-state">
            <div class="text">Match or Search</div>
          </th>
        {% endblock %}
      </tr>
      </thead>
      <tbody>
      {% block table_body %}
        {% for name, series in series_data.items %}
          <form action="{% url "admin:update-series" book_id=book.id %}" method="post">
            <tr class="{% cycle "row1" "row2" %}">
              {% csrf_token %}
              <td class="field-name">
                {% if series %}
                  {{ series.name }}
                {% else %}
                  <input type="text" name="name" value="{{ name }}" title="Series name">
                {% endif %}
              </td>
              <td class="field-year">
                {% if series %}
                  {{ series.start_year }}
                {% else %}
                  <input type="number" name="start_year" value="" title="Series start year">
                {% endif %}
              </td>
              <td class="field-select">
                {% if series %}
                  <i class="fa fa-check"></i>
                {% else %}
                  <button type="submit" name="original" value="{{ name }}" class="btn btn-success btn-xs">Search...
                  </button>
                {% endif %}
              </td>
            </tr>
          </form>
        {% endfor %}
      {% endblock %}
      </tbody>
    </table>
  </div>
{% endblock %}

comiccollector/templates/books/series_results.html
{% extends 'books/series_matches.html' %}
{% load staticfiles %}

{% block intro %}
{% endblock %}

{% block table_header %}
  <th scope="col" class="column-name">
    <div class="text"><span>Series Name</span></div>
    <div class="clear"></div>
  </th>
  <th scope="col" class="column-start-year">
    <div class="text">Start Year</div>
    <div class="clear"></div>
  </th>
  <th scope="col" class="column-end-year">
    <div class="text">End Year</div>
    <div class="clear"></div>
  </th>
  <th scope="col" class="column-state">
    <div class="text">Action</div>
  </th>
{% endblock %}

{% block table_body %}
  {% for series in results %}
    <tr class="{% cycle "row1" "row2" %}">
      {% csrf_token %}
      <td class="field-name">
        {{ series.name }}
      </td>
      <td>
        {{ series.start_year }}
      </td>
      <td>
        {% if series.end_year != 9999 %}
          {{ series.end_year }}
        {% else %}
          ongoing
        {% endif %}
      </td>
      <td>
        <form action="{% url "admin:update-series" book_id=book.id %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="original" value="{{ original }}">
          <input type="hidden" name="name" value="{{ series.name }}">
          <input type="hidden" name="start_year" value="{{ series.start_year }}">
          <input type="hidden" name="end_year" value="{{ series.end_year }}">
          <button type="submit" name="add" value="add">Add...</button>
        </form>
      </td>
    </tr>
  {% endfor %}
{% endblock %}